// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models
{
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string FullName { get; set; }
        public string CusCode { get; set; }
        public string Location { get; set; }
    }
}